import type { Astrologer, Transaction, ChatMessage } from './types';

export const astrologers: Astrologer[] = [
  {
    id: '1',
    name: 'Astro Neha',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1888&auto=format&fit=crop',
    skills: ['Vedic', 'Tarot', 'Numerology'],
    experience: 10,
    rating: 4.9,
    reviews: 1204,
    price: 25,
    language: 'Hindi',
    status: 'online',
    bio: 'Expert in Vedic astrology with a decade of experience in solving life problems.',
  },
  {
    id: '2',
    name: 'Guru Ramesh',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1887&auto=format&fit=crop',
    skills: ['Vastu', 'Palmistry'],
    experience: 15,
    rating: 4.8,
    reviews: 987,
    price: 30,
    language: 'English',
    status: 'busy',
    bio: 'Vastu and Palmistry specialist helping clients achieve harmony and success.',
  },
  {
    id: '3',
    name: 'Priya Sharma',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=1961&auto=format&fit=crop',
    skills: ['Tarot Reader', 'Psychic'],
    experience: 8,
    rating: 4.9,
    reviews: 2341,
    price: 20,
    language: 'English',
    status: 'online',
    bio: 'Intuitive Tarot reader and psychic providing clarity and guidance for your journey.',
  },
  {
    id: '4',
    name: 'Ankit Patel',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1887&auto=format&fit=crop',
    skills: ['KP System', 'Numerology'],
    experience: 5,
    rating: 4.7,
    reviews: 754,
    price: 15,
    language: 'Hindi',
    status: 'away',
    bio: 'Specializing in KP astrology and numerology to provide accurate predictions.',
  },
  {
    id: '5',
    name: 'Divya Singh',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1887&auto=format&fit=crop',
    skills: ['Vedic', 'Face Reading'],
    experience: 12,
    rating: 4.8,
    reviews: 1500,
    price: 28,
    language: 'English',
    status: 'online',
    bio: 'Combining ancient Vedic wisdom with the art of face reading to reveal your destiny.',
  },
  {
    id: '6',
    name: 'Rajesh Kumar',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1887&auto=format&fit=crop',
    skills: ['Nadi Astrology', 'Prashna'],
    experience: 20,
    rating: 4.9,
    reviews: 3200,
    price: 40,
    language: 'Tamil',
    status: 'busy',
    bio: 'Master of Nadi Astrology, uncovering past, present, and future from ancient palm leaves.',
  },
  {
    id: '7',
    name: 'Astro Kavya',
    avatar: 'https://images.unsplash.com/photo-1557053910-d9eadeed1c58?q=80&w=1887&auto=format&fit=crop',
    skills: ['Vedic', 'Prashna'],
    experience: 9,
    rating: 4.8,
    reviews: 850,
    price: 22,
    language: 'Kannada',
    status: 'online',
    bio: 'Expert in Vedic astrology with deep knowledge of Prashna kundali.',
  },
  {
    id: '8',
    name: 'Pandit Sriram',
    avatar: 'https://images.unsplash.com/photo-1566753323558-f4e0952af115?q=80&w=1921&auto=format&fit=crop',
    skills: ['Numerology', 'Palmistry'],
    experience: 12,
    rating: 4.7,
    reviews: 1100,
    price: 27,
    language: 'Telugu',
    status: 'online',
    bio: 'Providing guidance through the science of numbers and the art of palmistry.',
  },
];

export const transactions: Transaction[] = [
  { id: 'txn1', date: '2023-10-26', description: 'Wallet Recharge', amount: 500, type: 'credit', status: 'success' },
  { id: 'txn2', date: '2023-10-25', description: 'Chat with Astro Neha', amount: 150, type: 'debit', status: 'success' },
  { id: 'txn3', date: '2023-10-24', description: 'Wallet Recharge', amount: 200, type: 'credit', status: 'success' },
  { id: 'txn4', date: '2023-10-22', description: 'Call with Guru Ramesh', amount: 300, type: 'debit', status: 'success' },
  { id: 'txn5', date: '2023-10-20', description: 'Failed Recharge', amount: 100, type: 'credit', status: 'failed' },
];

export const chatMessages: ChatMessage[] = [];
